[TMainForm.LossesTest] =======================================================
[TMainForm.LossesTest] FuncName=CosineSimilarity
[TMainForm.LossesTest] yTrue=[0.62944738,0.74602638,0.2647185,0.44300356,0.91501366,0.68477385,0.9143339,0.60056095,0.15647743,0.58441465,0.31148139,0.69825861,0.35747032,0.48626494,0.31095579,0.41209217,0.44615404,0.80573645,0.38965724,0.90044409,0.12251128,0.53103358,0.62625479,0.1088276,0.41872966]
[TMainForm.LossesTest] yPred=[0.81158387,0.82675171,0.8049192,0.09376304,0.92977707,0.94118556,0.0292487,0.71622731,0.83147105,0.91898485,0.92857664,0.86798649,0.51548025,0.21554596,0.65762662,0.93633431,0.90765722,0.64691565,0.36580104,0.93110784,0.23688308,0.59039981,0.02047121,0.29262602,0.50937336]
[TMainForm.LossesTest] Loss=-0.8449463
[TMainForm.LossesTest] grad=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
=======================================================
---- X:\Projects\KR\Test\NeuralNetwork\nn\tests\py\losses.py
Traceback (most recent call last):
  File "X:\Projects\KR\Test\NeuralNetwork\nn\tests\py\losses.py", line 56, in <module>
    loss_value = loss_fn(y_true, y_pred)
                 ^^^^^^^
NameError: name 'loss_fn' is not defined

[TMainForm.LossesTest] ERROR: not FileExists('X:\Projects\KR\Test\NeuralNetwork\nn\tests\data\20250812\losses_CosineSimilarity_121601\loss.dat')
[TMainForm.LossesTest] ERROR: not FileExists('X:\Projects\KR\Test\NeuralNetwork\nn\tests\data\20250812\losses_CosineSimilarity_121601\grads.dat')
